### ISSUE TITLE
[Tech] Fix deployment builds to work with paywalled FontAwesome

### ISSUE THREAD

**Issue by argasek** [KoalicjaOtwartyKrakow/frontend#79]
```
steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
    - config 
    - set 
    - "@fortawesome:registry" 
    - https://npm.fontawesome.com/
  entrypoint: npm
- name: 'gcr.io/cloud-builders/docker' 
  args:
    - config 
    - set 
    - "//npm.fontawesome.com/:_authToken" 
    - $FONTAWESOME_TOKEN
  entrypoint: npm
  secretEnv: ['FONTAWESOME_TOKEN']
```

```
availableSecrets:
  secretManager:
  - versionName: projects/396614679188/secrets/fontawesome_token/versions/1
    env: 'FONTAWESOME_TOKEN'
```
